### ISSUE TITLE
GraphQL query to retrieve blog social links in header v17 native

### ISSUE THREAD

**Issue by monacodelisa** [monacodelisa/Angular-Headless-Hashnode#95] opened 2024-02-15 10:52 UTC
# Angular App version

- [ ] `angular-v16` - has no UI libraries
- [ ] `angular-v16-AnguMAT` - has Angular Material
- [ ] `angular-v16-PrimeNG` - has PrimeNG 
- [x] `angular-v17` - has no UI libraries
- [ ] `angular-v17-AnguMAT` - has Angular Material
- [ ] `angular-v17-PrimeNG` - has PrimeNG 
- [ ] `angular-hashnode`- presentation site

**Additional context**
- social links, key value pairs, with font awesome setup

in v16 I am using the keyvalue pipe:

```
    <div class="social">
      <div class="social-link" *ngFor="let social of blogSocialLinks | keyvalue">
        <a *ngIf="social.value && social.key !== 'website'" href="{{social.value}}" target="_blank" rel="noopener noreferrer">
          <i class="fa-brands fa-{{social.key}}"></i>
        </a>
        <a *ngIf="social.value && social.key === 'website'" href="{{social.value}}" target="_blank" rel="noopener noreferrer">
          <i class="fa-solid fa-globe"></i>
        </a>
      </div>
    </div>
```

need help in figuring out how to do this with the new control flow in v17 because 
I've tried 
```
      @for (social of blogSocialLinks | keyvalue; track social) {
        <div class="social-link">
          @if (social.value && social.key !== 'website') {
            <a href="{{social.value}}" target="_blank" rel="noopener noreferrer">
              <i class="fa-brands fa-{{social.key}}"></i>
            </a>
          }
          @if (social.value && social.key === 'website') {
            <a href="{{social.value}}" target="_blank" rel="noopener noreferrer">
              <i class="fa-solid fa-globe"></i>
            </a>
          }
        </div>
      }
```
but that doesn't work

**Comment by yshashi** [comment] 2024-02-19 14:00
You can assign it to me, I will take a look!

**Comment by yshashi** [comment] 2024-02-19 17:41
The issue is fixed so closing this issue!
Thanks!

**Closed by yshashi** 2024-02-19 17:41 UTC
Labels: 💁 help wanted, 🤝 contributions welcome, GraphGL, ⬜ no UI lib, 🅰️ v17, apollo angular

**Comment by monacodelisa** [comment] 2024-02-19 18:25
> The issue is fixed so closing this issue! Thanks!

great thank you
